[package]
name = "shinyai-raspi-pico-etude"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
panic-halt = "1.0.0"
rp235x-hal = { version = "0.4.0", features = ["binary-info", "critical-section-impl", "rt"] }

[profile.dev]
codegen-units = 1
debug = 2
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
lto = "fat"
opt-level = "s"
